services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    volumes:
      - .:/app
    tty: true
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always  # для автоматического перезапуска

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A myproject worker -l info
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - web  # чтобы убедиться, что Django запущен

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A myproject beat -l info
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - web  # чтобы убедиться, что Django запущен
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  pgdata:
